### ISSUE TITLE
Can't run main.py

### ISSUE THREAD

**Issue by Adam-Hoelscher** [Adam-Hoelscher/relative-imports-python3#1]
```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from . import script123
ImportError: attempted relative import with no known parent package
```

**Comment by s4m-mo** [comment]
Was your terminal navigated to the correct directory? What IDE do you use?

**Comment by Adam-Hoelscher** [comment]
No IDE here. I created the files using vim. My working directory is the top level of this repo.

```
$ git clone git@github.com:Adam-Hoelscher/relative-imports-python3.git
Cloning into 'relative-imports-python3'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), done.

$ cd relative-imports-python3/

$ python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from . import script123
ImportError: attempted relative import with no known parent package
```

**Comment by s4m-mo** [comment]
Hmmm... I really  don't know how I can help. Have you tried running it with any other editors/just from the command line normally. That was the only thing that fixed it for me, trying it in Vim.

**Comment by s4m-mo** [comment]
I am not very experienced, however, in Vim, so I might be missing a trick. If not, I am sorry, but I don't think I know what is the issue. Will run a few tests.

**Comment by s4m-mo** [comment]
Aha! Solved

**Comment by s4m-mo** [comment]
What you need to do is change `from . import script123` to `import script123`. It should then work perfectly.

The only reason you ever need to use `from .` is when the file you have create  shares the same name as an installed Python package.

**Comment by Adam-Hoelscher** [comment]
> What you need to do is change `from . import script123` to `import script123`. It should then work perfectly.
> 
> The only reason you ever need to use `from .` is when the file you have create shares the same name as an installed Python package.

I could have sworn I had tried this before, but it definitely worked this time. Thanks for your help.
